name: Docker image CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: mv .env.example .env

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
          run_install: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build & Re-Tag images
        run: |
          docker compose build
          docker tag hoppscotch-hoppscotch-backend ghcr.io/swisspost/hoppscotch/hoppscotch-backend:latest
          docker tag hoppscotch-hoppscotch-app ghcr.io/swisspost/hoppscotch/hoppscotch-app:latest
          docker tag hoppscotch-hoppscotch-sh-admin ghcr.io/swisspost/hoppscotch/hoppscotch-sh-admin:latest

      - name: Push images
        run: |
          docker push ghcr.io/swisspost/hoppscotch/hoppscotch-backend:latest
          docker push ghcr.io/swisspost/hoppscotch/hoppscotch-app:latest
          docker push ghcr.io/swisspost/hoppscotch/hoppscotch-sh-admin:latest
