name: Docker Image CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  packages: write

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["lts/*"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environment
        run: mv .env.example .env

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build images
        run: |
          cp .env.example .env
          pnpm --filter "hoppscotch-backend" exec prisma migrate deploy
          docker compose build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Re-Tag & Push images
        run: |
          docker tag hoppscotch-hoppscotch-backend ghcr.io/swisspost/hoppscotch-backend:latest
          docker tag hoppscotch-hoppscotch-app ghcr.io/swisspost/hoppscotch-app:latest
          docker tag hoppscotch-hoppscotch-sh-admin ghcr.io/swisspost/hoppscotch-sh-admin:latest
          docker push ghcr.io/swisspost/hoppscotch-backend:latest
          docker push ghcr.io/swisspost/hoppscotch-app:latest
          docker push ghcr.io/swisspost/hoppscotch-sh-admin:latest
